# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('genre_id', models.IntegerField()),
                ('genre_name', models.CharField(max_length=255)),
                ('ratings_id', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='PopularMovie',
            new_name='PopMovie',
        ),
        migrations.RenameModel(
            old_name='PopularPlan',
            new_name='PopPlan',
        ),
        migrations.RenameModel(
            old_name='PopularShow',
            new_name='PopShow',
        ),
        migrations.DeleteModel(
            name='PopularGenre',
        ),
    ]
